apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-sentinel-config
  namespace: trade-sentinel
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "tradedb"
  DATABASE_USER: "postgres"
