apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trade-sentinel-backend
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - trade-sentinel
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
